peacockr: Fix problems with submodule
Fixes:
```
  Installing peacockr-frontend v0.3.1 (~/workspace/TurrisOS/packages-crashlab-omnia-ng/build/build_dir/target-aarch64_cortex-a73+neon-vfpv4_musl/peacockr-0.3.1/frontend)
    Updating git submodule `https://openwrt.turris.cz/project/uci.git`
warning: spurious network error (3 tries remaining): invalid content-type: 'application/octet-stream'; class=Http (34)
warning: spurious network error (2 tries remaining): invalid content-type: 'application/octet-stream'; class=Http (34)
warning: spurious network error (1 try remaining): invalid content-type: 'application/octet-stream'; class=Http (34)
error: failed to get `ucifer` as a dependency of package `peacockr-backend v0.3.1 (~/workspace/TurrisOS/packages-crashlab-omnia-ng/build/build_dir/target-aarch64_cortex-a73+neon-vfpv4_musl/peacockr-0.3.1/backend)`

Caused by:
  failed to load source for dependency `ucifer`

Caused by:
  Unable to update https://gitlab.nic.cz/turris/ucifer.git#4bc55f16

Caused by:
  failed to update submodule `impl-tests/libuci/uci`

Caused by:
  failed to fetch submodule `impl-tests/libuci/uci` from https://openwrt.turris.cz/project/uci.git

Caused by:
  network failure seems to have happened
  if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  invalid content-type: 'application/octet-stream'; class=Http (34)
make[2]: *** [Makefile:68: ~/workspace/TurrisOS/packages-crashlab-omnia-ng/build/build_dir/target-aarch64_cortex-a73+neon-vfpv4_musl/peacockr-0.3.1/.built] Error 101
make[2]: Leaving directory '~/workspace/TurrisOS/packages-crashlab-omnia-ng/build/feeds/turrispackages/gui/peacockr'
time: package/feeds/turrispackages/peacockr/compile#0.25#0.13#11.31
    ERROR: package/feeds/turrispackages/peacockr failed to build.
```