pyzmq: Update to version 25.1.0
The previous version 22.3.0 would no longer compile with
OpenWRT 23.0.5/master.

zmq/backend/cython/_version.c:217:12: fatal error: longintrepr.h: No such file or directory
  217 |   #include longintrepr.h
      |            ^~~~~~~~~~~~~~~
compilation terminated.

Signed-off-by: Magnus Kessler <Magnus.Kessler@gmx.net>