resolver-debug: Copy resolver conf for logrotate with correct permissions
Currently, the config file ended up with permissions 0664 instead of
0644. This caused the cronjob of logrotate ignore the config file.

Error:
```
warning: Potentially dangerous mode on resolver.conf: 0664
error: Ignoring resolver.conf because it is writable by group or others.
error: found error in file resolver.conf, skipping
```