suricata-bin: disable stack-protector
Stack protector causes linker errors on musl with 32-bit PowerPC
because musl doesn't provide __stack_chk_fail_local symbol that
GCC generates for PIC code with -fstack-protector.

Rust's cc crate compiles vendored C code (like libz-sys zlib) with
stack protection enabled by default, which fails during linking:

  error: linking with `powerpc-openwrt-linux-gcc` failed: exit status: 1
  |
  = note: ld: ... undefined reference to `__stack_chk_fail_local'
          collect2: error: ld returned 1 exit status

Signed-off-by: Josef Schlehofer <pepe.schlehofer@gmail.com>